### ISSUE TITLE
what, if any, mechanism exists for setting a value completely to null

### ISSUE THREAD

**Issue by recursivelycurious** [recursivelycurious/helm-sandbox#1]
The doc example for liveness probes illustrates eliminating a mutually exclusive duplicate [here](https://docs.helm.sh/chart_template_guide/#deleting-a-default-key) but this does not work as expected with values I simply wish to remove?

`--set favorite.drink=null helm-sandbox/`

produced

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: smelly-buffoon-configmap
data:
  myvalue: "Hello World"
  drink: "null"
  food: "salmon"
```
